# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      environment_name: 
        description: 'environment_name'
        required: true
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: do ls
      run: |
         ls -al
      shell: bash
    - name: Checkout code
      uses: actions/checkout@v2
    - name: create environment
      uses: ahmadiesa-abu/create-environment-action@v1.2
      with:
        environment-name: ${{ github.event.inputs.environment_name }}
        blueprint: blueprint.yaml
        labels: test1:true,test2:false

    - name: get environment data
      uses: ahmadiesa-abu/environment-data-labels-action@v1.2
      with:
        environment-name: ${{ github.event.inputs.environment_name }}
        labels: test1:true,test2:false
        outputs-file: env-data.json

    - name: Upload environment data
      uses: actions/upload-artifact@v2
      with:
        name: simple-env-data
        path: env-data.json

    - name: delete-environment
      id: delete_environment
      uses: ahmadiesa-abu/delete-environment-action@v1.2
      with:
        environment-name: ${{ github.event.inputs.environment_name }}
        labels: test1:true,test2:false

env:
  CLOUDIFY_HOST: ${{ secrets.CLOUDIFY_HOST }}
  CLOUDIFY_USERNAME: ${{ secrets.CLOUDIFY_USERNAME }}
  CLOUDIFY_PASSWORD: ${{ secrets.CLOUDIFY_PASSWORD }}
  CLOUDIFY_TENANT: dev_tenant
  CLOUDIFY_SSL: ${{ secrets.CLOUDIFY_SSL }}
  CLOUDIFY_SSL_TRUST_ALL: ${{ secrets.CLOUDIFY_SSL_TRUST_ALL }}
