name: filter commit nessage
on:
  issue_comment:
    types: [created]
jobs:
  example:
    runs-on: ubuntu-latest
    environment: 'test'
    steps:
      - id: execute_command
        name: Execute cloudify command from comment
        if: ${{ github.event.issue.pull_request }}
        uses: ahmadiesa-abu/cli-action@v1.0.0
        with:
          command: ${{ github.event.comment.body }}

      - id: formatted_command
        name: format command output
        run: |
          cli-output=fromJSON(${{steps.execute_command.outputs.cli-output}})
          cli-output="${cli-output//'%'/'%25'}"
          cli-output="${cli-output//$'\n'/'%0A'}"
          cli-output="${cli-output//$'\r'/'%0D'}"
          echo ::set-output name=cli-output::$cli-output


      - name: Create comment
        # run: echo ${{ steps.execute_command.outputs.cli-output }}
        uses: peter-evans/create-or-update-comment@v1.4.5
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            ${{ steps.formatted_command.outputs.cli-output }}

env:
  CLOUDIFY_HOST: ${{ secrets.CLOUDIFY_HOST }}
  CLOUDIFY_USERNAME: ${{ secrets.CLOUDIFY_USERNAME }}
  CLOUDIFY_PASSWORD: ${{ secrets.CLOUDIFY_PASSWORD }}
  CLOUDIFY_TENANT: default_tenant
  CLOUDIFY_SSL: ${{ secrets.CLOUDIFY_SSL }}
  CLOUDIFY_SSL_TRUST_ALL: ${{ secrets.CLOUDIFY_SSL_TRUST_ALL }}
