name: filter commit nessage
on:
  issue_comment:
    types: [created]
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - id: execute_command
        name: Execute cloudify command from comment
        if: ${{ github.event.issue.pull_request }}
        uses: ahmadiesa-abu/cli-action@v1.0.0
        with:
          command: ${{ github.event.comment.body }}

      - id: format_output
        run: |
          cli-output="${cli-output//$'\n'/'%0A'}"
          echo "::set-output name=cli-output::$cli-output"

      - name: Create comment
        # run: echo ${{ steps.execute_command.outputs.cli-output }}
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          comment-author: 'Cloudify'
          body: |
            ${{ steps.format_output.outputs.cli-output }}

env:
  CLOUDIFY_HOST: ${{ secrets.CLOUDIFY_HOST }}
  CLOUDIFY_USERNAME: ${{ secrets.CLOUDIFY_USERNAME }}
  CLOUDIFY_PASSWORD: ${{ secrets.CLOUDIFY_PASSWORD }}
  CLOUDIFY_TENANT: default_tenant
  CLOUDIFY_SSL: ${{ secrets.CLOUDIFY_SSL }}
  CLOUDIFY_SSL_TRUST_ALL: ${{ secrets.CLOUDIFY_SSL_TRUST_ALL }}
