name: filter commit nessage
on:
  issue_comment:
    types: [created]
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - id: execute_command
        name: Execute cloudify command from comment
        if: ${{ github.event.issue.pull_request }}
        uses: jrzeszutek/cli-action@v1.2.1
        with:
          command: ${{ github.event.comment.body }}
          set-output: false

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            ${{ toJSON(steps.execute_command.outputs) }}

env:
  CLOUDIFY_HOST: ${{ secrets.CLOUDIFY_HOST }}
  CLOUDIFY_USERNAME: ${{ secrets.CLOUDIFY_USERNAME }}
  CLOUDIFY_PASSWORD: ${{ secrets.CLOUDIFY_PASSWORD }}
  CLOUDIFY_TENANT: default_tenant
  CLOUDIFY_SSL: ${{ secrets.CLOUDIFY_SSL }}
  CLOUDIFY_SSL_TRUST_ALL: ${{ secrets.CLOUDIFY_SSL_TRUST_ALL }}
