name: filter commit nessage
on:
  issue_comment:
    types: [created]
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Execute for pull request comments only
        if: ${{ github.event.issue.pull_request }}
        run: echo ${{ toJSON(github.event) }}


env:
  CLOUDIFY_HOST: ${{ secrets.CLOUDIFY_HOST }}
  CLOUDIFY_USERNAME: ${{ secrets.CLOUDIFY_USERNAME }}
  CLOUDIFY_PASSWORD: ${{ secrets.CLOUDIFY_PASSWORD }}
  CLOUDIFY_TENANT: default_tenant
  CLOUDIFY_SSL: ${{ secrets.CLOUDIFY_SSL }}
  CLOUDIFY_SSL_TRUST_ALL: ${{ secrets.CLOUDIFY_SSL_TRUST_ALL }}
